SET SERVEROUTPUT ON 
CREATE TRIGGER bustedmovie
	BEFORE DELETE ON Movie 
	REFERENCING OLD AS oldRow 
	FOR EACH ROW 
	BEGIN 
		DELETE FROM STARSIN WHERE STARSIN.MOVIETITLE = :oldRow.Title; 
END bustedmovie; 