SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE NoMoreStars (
    p_Name IN MOVIESTAR.Name%TYPE) AS
BEGIN
    DELETE FROM MOVIESTAR WHERE MOVIESTAR.Name = p_Name; 
    DELETE FROM STARSIN WHERE STARSIN.StarName = p_Name; 
END NoMoreStars;
